version: "3.8"

services:
  auth-service:
    build: ./auth-service
    ports:
      - "3100:3100"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
      - consul
    networks:
      - microservices-network

  project-service:
    build: ./project-service
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
      - consul  # Ajout de la dépendance à Consul
    networks:
      - microservices-network
        project-service:
    build: ./project-service
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
      - consul  # Ajout de la dépendance à Consul
    networks:
      - microservices-network
        project-service:
    build: ./project-service
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
      - consul  # Ajout de la dépendance à Consul
    networks:
      - microservices-network
        project-service:
    build: ./project-service
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
      - consul  # Ajout de la dépendance à Consul
    networks:
      - microservices-network
        project-service:
    build: ./project-service
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
      - consul  # Ajout de la dépendance à Consul
    networks:
      - microservices-network
        project-service:
    build: ./project-service
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
      - consul  # Ajout de la dépendance à Consul
    networks:
      - microservices-network
        project-service:
    build: ./project-service
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
      - consul  # Ajout de la dépendance à Consul
    networks:
      - microservices-network

  mongo:
    image: mongo:6.0
    container_name: mongo-db
    ports:
      - "27017:27017"
    networks:
      - microservices-network

  consul:
    image: hashicorp/consul:latest
    container_name: consul-server
    ports:
      - "8500:8500"
    networks:
      - microservices-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"
      - "4318:4318"
    networks:
      - microservices-network

networks:
  microservices-network:
