version: '3.8'

services:
  mongo-auth:
    image: mongo
    ports:
      - "27017:27017"

  mongo-projects:
    image: mongo
    ports:
      - "27018:27017"

  mongo-tasks:
    image: mongo
    ports:
      - "27019:27017"

  mongo-reports:
    image: mongo
    ports:
      - "27020:27017"

  mongo-chat:
    image: mongo
    ports:
      - "27021:27017"

  auth-service:
    build:
      context: ./auth-service
    ports:
      - "3000:3000"
    depends_on:
      - mongo-auth

  project-service:
    build:
      context: ./project-service
    ports:
      - "3001:3001"
    depends_on:
      - mongo-projects

  task-service:
    build:
      context: ./task-service
    ports:
      - "3002:3002"
    depends_on:
      - mongo-tasks

  report-service:
    build:
      context: ./report-service
    ports:
      - "3003:3003"
    depends_on:
      - mongo-reports

  collaboration-service:
    build:
      context: ./collaboration-service
    ports:
      - "3004:3004"
    
  gateway:
    build:
      context: ./gateway
    ports:
      - "3005:3005"

  service-registry:
    build:
      context: ./service-registry
    ports:
      - "3006:3006"   
    depends_on:
      - auth-service
      - project-service
      - task-service
      - report-service
      - collaboration-service

  nginx:
    image: nginx
    volumes:
      - ../frontend/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - gateway
